### ISSUE TITLE
Why not use MachineID?

### ISSUE THREAD

**Issue by c64emulator** [shaddi/snowflake#5]
There is already a unique ID for each machine: the MachineID. See [https://wiki.debian.org/MachineID](https://wiki.debian.org/MachineID):
From man 5 machine-id:
   > The /etc/machine-id file contains the unique machine ID of the local system that is set during installation or boot.
       The machine ID is usually generated from a random source during system installation or first boot and stays constant for
       all subsequent boots.

There is already a package for it: [https://pypi.org/project/py-machineid/](https://pypi.org/project/py-machineid/)

**Comment by shaddi** [comment]
Sure, you can definitely use that if it meets your needs. When this project was created, systemd wasn't widely adopted on the platforms I used. I suppose the other difference is that this package will generate the ID when the Python package is installed, rather than at boot or install time, which in our experience was helpful when dealing with embedded devices flashed with the same base OS image then configured later. Thanks for pointing out that alternative!
